import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import "./Dashboard.css";
import {
    MessageSquare,
    FileText,
    Link as LinkIcon,
    AlignLeft,
    ShieldCheck,
    Image as ImageIcon,
    Code,
    PenTool,
    ArrowRight
} from "lucide-react";

const TOOLS = [
    {
        name: "AI Chat",
        href: "/chat",
        icon: MessageSquare,
        description: "Engage in intelligent conversations with our advanced AI assistant for any task."
    },
    {
        name: "ATS Resume Analyzer",
        href: "/resume-analyzer",
        icon: FileText,
        description: "Score your resume against industry standards and optimize it for ATS software."
    },
    {
        name: "URL Shortener",
        href: "/url-shortener",
        icon: LinkIcon,
        description: "Create sleek, memorable, and trackable short links instantly."
    },
    {
        name: "Document Summarizer",
        href: "/summarizer",
        icon: AlignLeft,
        description: "Distill long documents, web pages, or text into concise key points."
    },
    {
        name: "Image Detector",
        href: "/image-detector",
        icon: ShieldCheck,
        description: "Analyze images to determine if they were generated by AI models."
    },
    {
        name: "Image Generator",
        href: "/image-generator",
        icon: ImageIcon,
        description: "Transform your text prompts into stunning, high-quality visuals."
    },
    {
        name: "Code Explainer",
        href: "/code-explainer",
        icon: Code,
        description: "Understand complex code snippets, find bugs, and learn refactoring techniques."
    },
    {
        name: "Grammar & Style Checker",
        href: "/grammar-checker",
        icon: PenTool,
        description: "Perfect your writing with advanced grammar and tone suggestions."
    },
];

const containerVariants = {
    hidden: { opacity: 0 },
    show: {
        opacity: 1,
        transition: {
            staggerChildren: 0.05,
            delayChildren: 0.1
        }
    }
};

const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 300, damping: 24 } }
};

export default function Dashboard() {
    return (
        <div className="dashboard-container">
            {/* Animated Background Blobs */}
            <div className="dashboard-blob-1 animate-blob" />
            <div className="dashboard-blob-2 animate-blob animation-delay-2000" />
            <div className="dashboard-blob-3 animate-blob animation-delay-4000" />

            <div className="relative z-10 max-w-6xl mx-auto space-y-12">
                <header className="space-y-4 pt-10 pb-6 text-center lg:text-left">
                    <motion.div
                        initial={{ opacity: 0, y: -20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.3 }}
                        className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-sm font-medium text-primary mb-4"
                    >
                        <span className="relative flex h-2 w-2">
                            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
                            <span className="relative inline-flex rounded-full h-2 w-2 bg-primary"></span>
                        </span>
                        All systems operational
                    </motion.div>
                    <motion.h1
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ duration: 0.1 }}
                        className="text-4xl lg:text-6xl font-extrabold tracking-tight text-white mb-2 flex flex-wrap gap-x-4 gap-y-2 justify-center lg:justify-start"
                    >
                        {"Welcome to".split(" ").map((word, i) => (
                            <motion.span
                                key={i}
                                initial={{ opacity: 0, y: 10, filter: "blur(5px)" }}
                                animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                                transition={{
                                    duration: 0.4,
                                    delay: 0.1 + (i * 0.05),
                                    ease: [0.22, 1, 0.36, 1]
                                }}
                            >
                                {word}
                            </motion.span>
                        ))}
                        <motion.span
                            initial={{ opacity: 0, scale: 0.9, filter: "blur(5px)" }}
                            animate={{ opacity: 1, scale: 1, filter: "blur(0px)" }}
                            transition={{
                                duration: 0.5,
                                delay: 0.3,
                                ease: "easeOut"
                            }}
                            className="text-gradient"
                        >
                            DocZen
                        </motion.span>
                    </motion.h1>
                    <motion.p
                        initial={{ opacity: 0, y: -10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.4, delay: 0.15 }}
                        className="text-lg text-muted-foreground max-w-2xl mx-auto lg:mx-0"
                    >
                        Unleash the power of AI with our premium suite of professional tools. Analyze, generate, and optimize everything in one place.
                    </motion.p>
                </header>

                <motion.div
                    variants={containerVariants}
                    initial="hidden"
                    animate="show"
                    className="tool-grid"
                >
                    {TOOLS.map((tool) => (
                        <motion.div key={tool.name} variants={itemVariants}>
                            <Link to={tool.href} className="block group h-full">
                                <div className="tool-card">
                                    <div className="tool-card-glow" />

                                    <div className="tool-icon-wrapper">
                                        <tool.icon className="w-6 h-6 text-primary group-hover:text-white transition-colors" />
                                    </div>

                                    <h3 className="text-xl font-bold text-white mb-2 group-hover:text-primary transition-colors">
                                        {tool.name}
                                    </h3>

                                    <p className="text-sm text-muted-foreground flex-1 mb-6">
                                        {tool.description}
                                    </p>

                                    <div className="mt-auto flex items-center text-sm font-semibold text-primary/80 group-hover:text-primary transition-colors">
                                        Get Started <ArrowRight className="w-4 h-4 ml-1 opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 transition-all duration-300" />
                                    </div>
                                </div>
                            </Link>
                        </motion.div>
                    ))}
                </motion.div>
            </div>
        </div>
    );
}
